[package]
org = "ballerina"
name = "copybook"
version = "0.1.0"
distribution = "2201.8.0"

[build-options]
observabilityIncluded = true

[[platform.java17.dependency]]
path="../native/build/libs/copybook-1.0-SNAPSHOT.jar"

[[platform.java17.dependency]]
path="./lib/antlr4-runtime-4.13.1.jar"